// src/data/locations.ts

export type Location = {
  id: string
  image: string
  mapLink: string
  name: string
  inquiries: number
  reservations: number
  overall: string
  status: "Active" | "Inactive"
  minCapacity: number
  maxCapacity: number
  address: string
  primaryPhone: string
  secondaryPhone?: string
  attributes: string[]
  eventTypes: string[]
}

export const locations: Location[] = [
  {
    id: "1",
    image: "",
    mapLink: "",
    name: "Prof. Kathleen Strosin IV",
    inquiries: 4,
    reservations: 0,
    overall: "5/5",
    status: "Active",
    minCapacity: 70819863,
    maxCapacity: 5229348,
    address: "14938 Ella Ways Suite 323 Carlieview, MO 32821-8325",
    primaryPhone: "+12029430101",
    secondaryPhone: "(914) 997-2210",
    attributes: ["Venue Image", "No Link"],
    eventTypes: ["Wedding", "Birthday"],
  },
  {
    id: "2",
    image: "",
    mapLink: "https://maps.google.com",
    name: "Brenda Heller DVM",
    inquiries: 5,
    reservations: 0,
    overall: "5/5",
    status: "Active",
    minCapacity: 3604618,
    maxCapacity: 28024,
    address: "574 Aufderhar Garden Antwonstad, NC 22686-1055",
    primaryPhone: "+1 (747) 697-8791",
    secondaryPhone: "+1-585-610-1759",
    attributes: ["Venue Image", "No Link"],
    eventTypes: ["Wedding", "Birthday"],
  },
  {
    id: "3",
    image: "",
    mapLink: "https://maps.google.com",
    name: "Dr. Victor Emard",
    inquiries: 3,
    reservations: 0,
    overall: "3/5",
    status: "Active",
    minCapacity: 73369,
    maxCapacity: 92172142,
    address: "42739 Shirley Stream Apt. 735 West Alexane, AR 12005-0464",
    primaryPhone: "+19898513919",
    secondaryPhone: "520.760.1342",
    attributes: ["Venue Image", "No Link"],
    eventTypes: ["Wedding", "Birthday"],
  },
  {
    id: "4",
    image: "",
    mapLink: "https://maps.google.com",
    name: "Jeramie Schimmel",
    inquiries: 3,
    reservations: 0,
    overall: "3/5",
    status: "Active",
    minCapacity: 5,
    maxCapacity: 62889,
    address: "2552 McClure Island Leannhaven, SC 06515-8396",
    primaryPhone: "+1 (218) 935-1614",
    secondaryPhone: "+1.413.384.6336",
    attributes: ["Venue Image", "No Link"],
    eventTypes: ["Birthday", "Party"],
  },
  {
    id: "5",
    image: "",
    mapLink: "https://maps.google.com",
    name: "Jennyfer Stoltenberg DDS",
    inquiries: 5,
    reservations: 0,
    overall: "5/5",
    status: "Active",
    minCapacity: 489604145,
    maxCapacity: 842035,
    address: "77308 Genevieve Shore Apt. 750 Goyettechester, UT 13639",
    primaryPhone: "309-620-4218",
    secondaryPhone: "+1 (225) 823-9755",
    attributes: ["Venue Image", "No Link"],
    eventTypes: ["Birthday", "Party"],
  },
  {
    id: "6",
    image: "",
    mapLink: "https://maps.google.com",
    name: "Prof. Cade Kertzmann Sr.",
    inquiries: 2,
    reservations: 0,
    overall: "2/5",
    status: "Active",
    minCapacity: 8976,
    maxCapacity: 626811,
    address: "40351 Mathew Place Lake Amir, MI 34242-4208",
    primaryPhone: "936-638-2630",
    secondaryPhone: "1-856-576-7606",
    attributes: ["Venue Image", "No Link"],
    eventTypes: ["Wedding", "Birthday"],
  },
  {
    id: "7",
    image: "",
    mapLink: "https://maps.google.com",
    name: "Clarabelle Purdy",
    inquiries: 0,
    reservations: 0,
    overall: "N/A",
    status: "Active",
    minCapacity: 653,
    maxCapacity: 1095898,
    address: "18691 Nader Inlet Apt. 578 North Bethel, TX 68903",
    primaryPhone: "+1-361-728-2288",
    secondaryPhone: "+1.469.370.8857",
    attributes: ["Venue Image", "No Link"],
    eventTypes: ["Wedding", "Meeting"],
  },
  {
    id: "8",
    image: "",
    mapLink: "https://maps.google.com",
    name: "Prof. Dejon Hickle I",
    inquiries: 0,
    reservations: 0,
    overall: "N/A",
    status: "Active",
    minCapacity: 213324,
    maxCapacity: 783,
    address: "2936 Jessica Locks Rathshire, TN 90997",
    primaryPhone: "(207) 301-6466",
    secondaryPhone: "+1 (463) 798-9267",
    attributes: ["Venue Image", "No Link"],
    eventTypes: ["Wedding", "Birthday"],
  },
  {
    id: "9",
    image: "",
    mapLink: "https://maps.google.com",
    name: "Caesar Nikolaus V",
    inquiries: 1,
    reservations: 0,
    overall: "1/5",
    status: "Active",
    minCapacity: 35041237,
    maxCapacity: 3707887,
    address: "1088 Block Lodge Suite 472 South Gisselle, KS 01574",
    primaryPhone: "1-657-234-6244",
    secondaryPhone: "(361) 263-3301",
    attributes: ["Venue Image", "No Link"],
    eventTypes: ["Wedding", "Party"],
  },
  {
    id: "10",
    image: "",
    mapLink: "https://maps.google.com",
    name: "Caesar Nikolaus V",
    inquiries: 1,
    reservations: 0,
    overall: "1/5",
    status: "Active",
    minCapacity: 8674,
    maxCapacity: 933913825,
    address: "877 Beahan Square Suite 120 South Hollie, OH 05850-6433",
    primaryPhone: "(231) 654-9707",
    secondaryPhone: "253.587.0590",
    attributes: ["Venue Image", "No Link"],
    eventTypes: ["Wedding", "Party"],
  },
]

// Generate dummy venues 11–60
for (let i = 11; i <= 60; i++) {
  locations.push({
    id: i.toString(),
    image: "",
    mapLink: "https://maps.google.com",
    name: `Venue ${i}`,
    inquiries: Math.floor(Math.random() * 20) + 1,
    reservations: Math.floor(Math.random() * 15),
    overall: `${(Math.random() * (5 - 3.5) + 3.5).toFixed(1)}/5`,
    status: Math.random() > 0.5 ? "Active" : "Inactive",
    minCapacity: Math.floor(Math.random() * 50) + 20,
    maxCapacity: Math.floor(Math.random() * 300) + 100,
    address: `${i * 10} Example Street`,
    primaryPhone: `555-000-${1000 + i}`,
    secondaryPhone: i % 2 === 0 ? `555-999-${2000 + i}` : "",
    attributes: ["WiFi", "Parking", "Catering"].filter(() => Math.random() > 0.4),
    eventTypes: ["Wedding", "Birthday", "Conference", "Corporate Event", "Party"].filter(
      () => Math.random() > 0.5
    ),
  })
}
